package com.s2aglobal.tournmate.util

import android.app.Activity
import android.content.ClipData
import android.content.Context
import android.content.ContextWrapper
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Path
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.os.Build
import android.os.Bundle
import android.os.CancellationSignal
import android.os.ParcelFileDescriptor
import android.print.PageRange
import android.print.PrintAttributes
import android.print.PrintDocumentAdapter
import android.print.PrintDocumentInfo
import android.print.PrintManager
import android.text.TextUtils
import android.util.Log
import android.widget.Toast
import androidx.compose.ui.graphics.toArgb
import androidx.core.content.FileProvider
import com.s2aglobal.tournmate.domain.model.Match
import com.s2aglobal.tournmate.domain.model.MatchFormat
import com.s2aglobal.tournmate.domain.model.MatchStatus
import com.s2aglobal.tournmate.domain.model.Registration
import com.s2aglobal.tournmate.domain.model.Tournament
import com.s2aglobal.tournmate.ui.screen.tournament.BracketStandingsEntry
import com.s2aglobal.tournmate.ui.screen.tournament.StandingsEntry
import com.s2aglobal.tournmate.ui.theme.AppAccent
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.text.DateFormat
import kotlin.math.max
import kotlin.math.min

/**
 * Builds the Matches-tab PDF (Draw / Bracket, Matches, or Standings) and hands it
 * to the system share sheet or the print framework.
 *
 * Mirrors iOS `TournamentDetailView.shareCurrentTabAsPDF()` + `PDFDocumentWrapper`:
 *  - header: title, tab name, trophy, venue · date · format, divider
 *  - the tab's content (same tables / match lists / draw layout as iOS)
 *  - footer: "Generated by TournMate" · "www.tournmate.com"
 *  - US Letter portrait for Matches / Standings, A4 landscape for Draw / Bracket;
 *    a single page shrinks to the content height, longer content flows onto
 *    full-height pages (whole rows, never cut in half).
 */
object TournamentPdfExporter {

    /** Everything the PDF needs, computed by the screen from its UI state. */
    class Input(
        val tournament: Tournament,
        val matches: List<Match>,
        val registrations: List<Registration>,
        val totalBracketRounds: Int,
        val rrStandings: List<StandingsEntry>,
        val groupStandings: Map<String, List<StandingsEntry>>,
        val bracketProgress: List<BracketStandingsEntry>,
        /** "Ties: …" captions under the round-robin and group tables (`StandingsEntry.tieBreakCaption`). */
        val rrTieBreakCaption: String = "",
        val groupTieBreakCaption: String = "",
    )

    // ── Public API ───────────────────────────────────────────────────────────

    /** Writes the PDF and opens the Android share sheet (application/pdf via FileProvider). */
    fun share(context: Context, input: Input, tabName: String) {
        val file = writePdf(context, input, tabName) ?: return toastFailure(context)
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val send = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, file.nameWithoutExtension)
            putExtra(Intent.EXTRA_TITLE, file.name)
            clipData = ClipData.newRawUri(file.name, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        val chooser = Intent.createChooser(send, file.name)
        if (context.findActivity() == null) chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(chooser)
    }

    /** Writes the same PDF and opens the system print dialog (printer or "Save as PDF"). */
    fun print(context: Context, input: Input, tabName: String) {
        val file = writePdf(context, input, tabName) ?: return toastFailure(context)
        val activity = context.findActivity() ?: return toastFailure(context)
        val printManager = activity.getSystemService(Context.PRINT_SERVICE) as PrintManager
        val landscape = isDrawTab(tabName)
        val attributes = PrintAttributes.Builder()
            .setMediaSize(if (landscape) PrintAttributes.MediaSize.ISO_A4.asLandscape() else PrintAttributes.MediaSize.NA_LETTER)
            .setColorMode(PrintAttributes.COLOR_MODE_COLOR)
            .build()
        printManager.print(file.nameWithoutExtension, FilePrintAdapter(file), attributes)
    }

    /** Renders the PDF into the app cache (covered by `file_provider_paths.xml`). Returns null on failure. */
    fun writePdf(context: Context, input: Input, tabName: String): File? = try {
        val dir = File(context.cacheDir, "pdf").apply { mkdirs() }
        val safeTitle = input.tournament.title.replace(Regex("[\\\\/:*?\"<>|]"), "-").trim().ifEmpty { "Tournament" }
        val file = File(dir, "$safeTitle - $tabName.pdf")
        val doc = render(input, tabName)
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()
        file
    } catch (e: Exception) {
        Log.e("TournamentPdf", "PDF export failed", e)
        null
    }

    // ── Print adapter (streams the pre-rendered file) ────────────────────────

    private class FilePrintAdapter(private val file: File) : PrintDocumentAdapter() {
        override fun onLayout(
            oldAttributes: PrintAttributes?, newAttributes: PrintAttributes,
            cancellationSignal: CancellationSignal?, callback: LayoutResultCallback, extras: Bundle?,
        ) {
            if (cancellationSignal?.isCanceled == true) { callback.onLayoutCancelled(); return }
            val info = PrintDocumentInfo.Builder(file.name)
                .setContentType(PrintDocumentInfo.CONTENT_TYPE_DOCUMENT)
                .setPageCount(PrintDocumentInfo.PAGE_COUNT_UNKNOWN)
                .build()
            callback.onLayoutFinished(info, oldAttributes != newAttributes)
        }

        override fun onWrite(
            pages: Array<out PageRange>?, destination: ParcelFileDescriptor,
            cancellationSignal: CancellationSignal?, callback: WriteResultCallback,
        ) {
            if (cancellationSignal?.isCanceled == true) { callback.onWriteCancelled(); return }
            try {
                FileInputStream(file).use { input ->
                    FileOutputStream(destination.fileDescriptor).use { output -> input.copyTo(output) }
                }
                callback.onWriteFinished(arrayOf(PageRange.ALL_PAGES))
            } catch (e: Exception) {
                Log.e("TournamentPdf", "Print write failed", e)
                callback.onWriteFailed(e.message)
            }
        }
    }

    // ── Layout model ─────────────────────────────────────────────────────────

    /** A vertical slice of the document that is never split across pages. */
    private class Block(val height: Float, val draw: (Canvas, Float, Float) -> Unit)

    private fun isDrawTab(tabName: String) = tabName == "Bracket" || tabName == "Draw"

    private fun render(input: Input, tabName: String): PdfDocument {
        val landscape = isDrawTab(tabName)
        val pageW = if (landscape) 842f else 612f
        val pageH = if (landscape) 595f else 792f
        val ctx = Ctx(input, pageW)

        val blocks = mutableListOf<Block>()
        blocks += ctx.header(tabName)
        val content = when (tabName) {
            "Bracket" -> ctx.bracketContent()
            "Draw" -> ctx.drawContent()
            "Standings" -> ctx.standingsContent()
            else -> ctx.matchesContent()
        }
        blocks += content
        blocks += Block(12f) { _, _, _ -> } // content bottom padding
        blocks += ctx.footer()

        val total = blocks.sumOf { it.height.toDouble() }.toFloat()
        val doc = PdfDocument()
        if (total <= pageH) {
            // Single page sized to the content, like iOS.
            val page = doc.startPage(PdfDocument.PageInfo.Builder(pageW.toInt(), kotlin.math.ceil(total).toInt(), 1).create())
            page.canvas.drawColor(Color.WHITE)
            var y = 0f
            blocks.forEach { it.draw(page.canvas, 0f, y); y += it.height }
            doc.finishPage(page)
        } else {
            var pageNo = 1
            var page = doc.startPage(PdfDocument.PageInfo.Builder(pageW.toInt(), pageH.toInt(), pageNo).create())
            page.canvas.drawColor(Color.WHITE)
            val topMargin = 24f
            var y = 0f
            for (b in blocks) {
                if (y + b.height > pageH && y > topMargin) {
                    doc.finishPage(page)
                    pageNo++
                    page = doc.startPage(PdfDocument.PageInfo.Builder(pageW.toInt(), pageH.toInt(), pageNo).create())
                    page.canvas.drawColor(Color.WHITE)
                    y = topMargin
                }
                b.draw(page.canvas, 0f, y)
                y += b.height
            }
            doc.finishPage(page)
        }
        return doc
    }

    // ── Drawing context ──────────────────────────────────────────────────────

    private class Ctx(val input: Input, val pageW: Float) {
        val t = input.tournament
        val accent = AppAccent.toArgb()
        val orange = Color.rgb(0xFF, 0x95, 0x00)
        val green = Color.rgb(0x34, 0xC7, 0x59)
        val yellow = Color.rgb(0xFF, 0xCC, 0x00)
        val red = Color.rgb(0xFF, 0x3B, 0x30)
        val black = Color.BLACK
        val secondary = Color.rgb(0x8A, 0x8A, 0x8E)
        val tertiary = Color.rgb(0xC5, 0xC5, 0xC7)
        val gray = Color.rgb(0x8E, 0x8E, 0x93)
        val gray6 = Color.rgb(0xF2, 0xF2, 0xF7)
        val separator = Color.rgb(0xC6, 0xC6, 0xC8)
        val dividerColor = Color.rgb(0xE5, 0xE5, 0xEA)

        /** iOS content padding: 16 horizontal inside the page. */
        val contentX = 16f
        val contentW = pageW - 32f

        private val regMap = input.registrations.associateBy { it.id.toString().uppercase() }

        fun teamName(id: String?, fallback: Registration? = null): String {
            val reg = regMap[id?.uppercase()] ?: fallback?.takeIf { it.player.name.isNotEmpty() } ?: return "TBD"
            return listOfNotNull(reg.player.name, reg.partner?.name).joinToString(" & ")
        }

        fun nameA(m: Match) = teamName(m.teamAId, m.teamA)
        fun nameB(m: Match) = teamName(m.teamBId, m.teamB)
        fun aWon(m: Match) = m.winnerRegistrationId != null && m.winnerRegistrationId.equals(m.teamAId, ignoreCase = true)
        fun bWon(m: Match) = m.winnerRegistrationId != null && m.winnerRegistrationId.equals(m.teamBId, ignoreCase = true)
        fun finished(m: Match) = m.status == MatchStatus.FINISHED

        // Paint helpers
        fun paint(size: Float, color: Int = black, weight: Int = 400, mono: Boolean = false, tracking: Float = 0f) =
            Paint(Paint.ANTI_ALIAS_FLAG).apply {
                textSize = size
                this.color = color
                val family = if (mono) Typeface.MONOSPACE else Typeface.DEFAULT
                typeface = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) Typeface.create(family, weight, false)
                else Typeface.create(family, if (weight >= 600) Typeface.BOLD else Typeface.NORMAL)
                if (tracking != 0f) letterSpacing = tracking / size
            }

        fun fit(text: String, p: Paint, maxW: Float): String =
            if (maxW <= 0f) "" else TextUtils.ellipsize(text, android.text.TextPaint(p), maxW, TextUtils.TruncateAt.END).toString()

        /** Draws text with its line box's top at [top] (line height ≈ 1.2 × size). */
        fun text(c: Canvas, s: String, x: Float, top: Float, p: Paint, align: Paint.Align = Paint.Align.LEFT) {
            p.textAlign = align
            val fm = p.fontMetrics
            val lineH = p.textSize * 1.2f
            val baseline = top + (lineH - (fm.descent - fm.ascent)) / 2f - fm.ascent
            c.drawText(s, x, baseline, p)
        }

        fun lineH(size: Float) = size * 1.2f

        fun fill(color: Int) = Paint(Paint.ANTI_ALIAS_FLAG).apply { this.color = color; style = Paint.Style.FILL }
        fun stroke(color: Int, w: Float = 0.5f) = Paint(Paint.ANTI_ALIAS_FLAG).apply { this.color = color; style = Paint.Style.STROKE; strokeWidth = w }
        fun alpha(color: Int, a: Float) = Color.argb((a * 255).toInt(), Color.red(color), Color.green(color), Color.blue(color))

        fun spacer(h: Float) = Block(h) { _, _, _ -> }

        // ── Header / footer (PDFDocumentWrapper) ──────────────────────────────

        fun header(tabName: String): Block {
            val h = 16f + lineH(20f) + 4f + lineH(10f) + 6f + lineH(10f) + 6f + 1f + 8f
            return Block(h) { c, _, top ->
                val x = 24f
                var y = top + 16f
                text(c, fit(t.title, paint(20f, weight = 700), pageW - 48f - 40f), x, y, paint(20f, weight = 700))
                drawTrophy(c, pageW - 24f - 24f, y + 2f, 24f, accent)
                y += lineH(20f) + 4f
                text(c, tabName.uppercase(), x, y, paint(10f, accent, 900, tracking = 1f))
                y += lineH(10f) + 6f
                // venue · date · format, each with a small glyph like the iOS Labels
                val meta = paint(10f, secondary)
                val dateStr = DateFormat.getDateTimeInstance(DateFormat.MEDIUM, DateFormat.SHORT).format(t.date)
                var mx = x
                listOf(t.location to 0, dateStr to 1, t.matchFormat.displayName to 2).forEach { (label, glyph) ->
                    if (label.isEmpty()) return@forEach
                    drawMetaGlyph(c, glyph, mx, y + 1.5f, 9f, secondary)
                    mx += 13f
                    text(c, label, mx, y, meta)
                    mx += meta.measureText(label) + 16f
                }
                y += lineH(10f) + 6f
                c.drawLine(x, y, pageW - 24f, y, stroke(separator, 0.5f))
            }
        }

        fun footer(): Block = Block(lineH(8f) + 16f) { c, _, top ->
            val p = paint(8f, tertiary)
            text(c, "Generated by TournMate", 24f, top, p)
            text(c, "www.tournmate.com", pageW - 24f, top, p, Paint.Align.RIGHT)
        }

        fun drawTrophy(c: Canvas, x: Float, y: Float, s: Float, color: Int) {
            val p = fill(color)
            val cup = Path().apply {
                moveTo(x + s * 0.22f, y + s * 0.08f)
                lineTo(x + s * 0.78f, y + s * 0.08f)
                lineTo(x + s * 0.74f, y + s * 0.42f)
                quadTo(x + s * 0.5f, y + s * 0.62f, x + s * 0.26f, y + s * 0.42f)
                close()
            }
            c.drawPath(cup, p)
            val handle = stroke(color, s * 0.06f)
            c.drawArc(RectF(x + s * 0.06f, y + s * 0.12f, x + s * 0.32f, y + s * 0.38f), 90f, 180f, false, handle)
            c.drawArc(RectF(x + s * 0.68f, y + s * 0.12f, x + s * 0.94f, y + s * 0.38f), 270f, 180f, false, handle)
            c.drawRect(x + s * 0.45f, y + s * 0.55f, x + s * 0.55f, y + s * 0.75f, p)
            c.drawRoundRect(RectF(x + s * 0.3f, y + s * 0.75f, x + s * 0.7f, y + s * 0.88f), s * 0.03f, s * 0.03f, p)
        }

        /** 0 = map pin, 1 = calendar, 2 = court. */
        fun drawMetaGlyph(c: Canvas, kind: Int, x: Float, y: Float, s: Float, color: Int) {
            when (kind) {
                0 -> { c.drawCircle(x + s / 2, y + s / 2, s / 2, fill(color)); c.drawCircle(x + s / 2, y + s / 2, s / 6, fill(Color.WHITE)) }
                1 -> { c.drawRoundRect(RectF(x, y + 1f, x + s, y + s), 1.5f, 1.5f, stroke(color, 0.8f)); c.drawLine(x, y + s * 0.35f, x + s, y + s * 0.35f, stroke(color, 0.8f)) }
                else -> { c.drawRect(x, y + 1.5f, x + s, y + s - 0.5f, stroke(color, 0.8f)); c.drawLine(x + s / 2, y + 1.5f, x + s / 2, y + s - 0.5f, stroke(color, 0.8f)) }
            }
        }

        // ── Match box (pdfMatchBox) ───────────────────────────────────────────

        val boxRowH = 4f + lineH(9f) + 4f
        val boxH = boxRowH * 2 + 0.5f

        fun drawMatchBox(c: Canvas, m: Match, x: Float, y: Float, w: Float) {
            val done = finished(m)
            listOf(Triple(nameA(m), aWon(m), m.scoreA), Triple(nameB(m), bWon(m), m.scoreB)).forEachIndexed { i, (name, won, score) ->
                val rowTop = y + i * (boxRowH + 0.5f)
                val np = paint(9f, black, if (won) 700 else 400)
                val scoreP = paint(9f, black, 700)
                val scoreStr = if (done) "${score ?: 0}" else ""
                val scoreW = if (done) scoreP.measureText(scoreStr) + 6f else 0f
                text(c, fit(name, np, w - 12f - scoreW), x + 6f, rowTop + 4f, np)
                if (done) text(c, scoreStr, x + w - 6f, rowTop + 4f, scoreP, Paint.Align.RIGHT)
            }
            c.drawLine(x, y + boxRowH, x + w, y + boxRowH, stroke(dividerColor, 0.5f))
            val border = if (done) alpha(green, 0.4f) else alpha(separator, 0.2f)
            c.drawRoundRect(RectF(x, y, x + w, y + boxH), 4f, 4f, stroke(border, 0.5f))
        }

        // ── Columns of rounds, wrapped into bands that fit the page width ─────

        private class Column(val title: String, val matches: List<Match>)

        private fun roundColumns(columns: List<Column>, colW: Float, gap: Float, connector: Boolean, champion: Boolean): List<Block> {
            if (columns.isEmpty()) return emptyList()
            val unit = colW + gap
            val championW = if (champion) 70f else 0f
            val perBand = max(1, ((contentW - championW + gap) / unit).toInt())
            val bands = columns.chunked(perBand)
            val blocks = mutableListOf<Block>()
            bands.forEachIndexed { bandIdx, band ->
                val isLast = bandIdx == bands.lastIndex
                val tallest = band.maxOf { it.matches.size }
                val h = lineH(9f) + 6f + tallest * (boxH + 6f)
                blocks += Block(max(h, if (champion && isLast) 60f else 0f) + 10f) { c, _, top ->
                    var x = contentX
                    band.forEachIndexed { i, col ->
                        text(c, fit(col.title.uppercase(), paint(9f, accent, 900), colW), x, top, paint(9f, accent, 900))
                        var y = top + lineH(9f) + 6f
                        col.matches.forEach { m -> drawMatchBox(c, m, x, y, colW); y += boxH + 6f }
                        if (connector && (i < band.lastIndex || !isLast)) {
                            val lineY = top + 40f
                            c.drawLine(x + colW, lineY, x + colW + gap, lineY, stroke(alpha(accent, 0.3f), 1f))
                        }
                        x += unit
                    }
                    if (champion && isLast) drawChampion(c, x, top + 4f, 20f)
                }
            }
            return blocks
        }

        fun drawChampion(c: Canvas, x: Float, y: Float, icon: Float) {
            val labelP = paint(8f, secondary, 700)
            val w = max(icon, labelP.measureText("Champion")) + 20f
            val h = 10f + icon + 4f + lineH(8f) + 10f
            drawTrophy(c, x + (w - icon) / 2, y + 10f, icon, yellow)
            text(c, "Champion", x + w / 2, y + 10f + icon + 4f, labelP, Paint.Align.CENTER)
            c.drawRoundRect(RectF(x, y, x + w, y + h), 8f, 8f, stroke(alpha(yellow, 0.5f), 1f))
        }

        /** Bracket names for knockout formats; "Round N" for round robin, Swiss and manual draws (iOS `pdfRoundTitle`). */
        private fun roundName(round: Int) = when (t.matchFormat) {
            MatchFormat.SINGLE_ELIMINATION, MatchFormat.DOUBLE_ELIMINATION, MatchFormat.GROUP_KNOCKOUT ->
                Match.bracketRoundName(round, input.totalBracketRounds)
            else -> "Round $round"
        }

        /** Every match grouped by round (iOS `vm.matchesByRound`). */
        private val rounds: List<Pair<Int, List<Match>>> =
            input.matches.groupBy { it.round ?: 0 }.toSortedMap().map { (r, ms) -> r to ms.sortedBy { it.bracketPosition ?: 0 } }

        // ── Bracket tab (pdfBracketContent) ───────────────────────────────────

        fun bracketContent(): List<Block> =
            roundColumns(rounds.map { (r, ms) -> Column(roundName(r), ms) }, 180f, 20f, connector = true, champion = false)

        // ── Draw tab (pdfDrawVisualContent) ───────────────────────────────────

        fun drawContent(): List<Block> {
            val blocks = mutableListOf<Block>()
            val groupMatches = input.matches.filter { it.groupLabel != null }.groupBy { it.groupLabel!! }.toSortedMap()

            if (groupMatches.isNotEmpty()) {
                blocks += sectionTitle("GROUP STAGE", orange, 14f)
                blocks += groupCards(groupMatches)
                blocks += Block(8f + 16f + 2f + lineH(8f) + 8f) { c, _, top ->
                    val cx = contentX + contentW / 2
                    val cy = top + 8f + 8f
                    c.drawCircle(cx, cy, 8f, fill(accent))
                    val arrow = stroke(Color.WHITE, 1.4f)
                    c.drawLine(cx, cy - 4f, cx, cy + 4f, arrow)
                    c.drawLine(cx - 3.5f, cy + 0.5f, cx, cy + 4f, arrow)
                    c.drawLine(cx + 3.5f, cy + 0.5f, cx, cy + 4f, arrow)
                    text(c, "Top teams qualify", cx, top + 8f + 16f + 2f, paint(8f, secondary, 500), Paint.Align.CENTER)
                }
                blocks += Block(17f) { c, _, top -> c.drawLine(contentX, top + 8f, contentX + contentW, top + 8f, stroke(dividerColor, 0.5f)) }
            }

            blocks += sectionTitle(if (groupMatches.isEmpty()) "DRAW" else "KNOCKOUT STAGE", green, 14f)

            val knockoutCols = rounds.mapNotNull { (r, ms) ->
                val ko = ms.filter { it.groupLabel == null }
                if (ko.isEmpty()) null else Column(roundName(r), ko)
            }
            if (knockoutCols.isNotEmpty()) {
                blocks += roundColumns(knockoutCols, 160f, 12f, connector = false, champion = true)
            } else if (groupMatches.isNotEmpty()) {
                blocks += placeholderKnockout(groupMatches.keys.toList())
            }
            return blocks
        }

        fun sectionTitle(title: String, color: Int, size: Float, trackingPt: Float = 0f, topPad: Float = 0f): Block =
            Block(topPad + lineH(size) + 8f) { c, _, top -> text(c, title, contentX, top + topPad, paint(size, color, 900, tracking = trackingPt)) }

        private fun extractTeams(ms: List<Match>): List<String> {
            val seen = LinkedHashMap<String, String>()
            ms.forEach { m ->
                seen.getOrPut(m.teamAId.uppercase()) { nameA(m) }
                seen.getOrPut(m.teamBId.uppercase()) { nameB(m) }
            }
            return seen.values.toList()
        }

        private fun groupCards(groups: Map<String, List<Match>>): List<Block> {
            val labels = groups.keys.toList()
            val gap = 16f
            val perRow = max(1, min(labels.size, ((contentW + gap) / (140f + gap)).toInt()))
            val cardW = (contentW - gap * (perRow - 1)) / perRow
            return labels.chunked(perRow).map { row ->
                val teamsByLabel = row.associateWith { extractTeams(groups[it].orEmpty()) }
                val maxTeams = teamsByLabel.values.maxOf { it.size }
                val cardH = 8f + lineH(11f) + 4f + maxTeams * (lineH(9f) + 4f) + 2f + lineH(7f) + 8f
                Block(cardH + 16f) { c, _, top ->
                    row.forEachIndexed { i, label ->
                        val x = contentX + i * (cardW + gap)
                        var y = top + 8f
                        text(c, "Group $label", x + 8f, y, paint(11f, accent, 700))
                        y += lineH(11f) + 4f
                        teamsByLabel[label].orEmpty().forEachIndexed { idx, team ->
                            text(c, "$label${idx + 1}", x + 8f, y + 0.5f, paint(8f, accent, 700, mono = true))
                            text(c, fit(team, paint(9f), cardW - 16f - 24f), x + 8f + 24f, y, paint(9f))
                            y += lineH(9f) + 4f
                        }
                        text(c, "Top ${t.formatConfig.advancingPerGroup} advance", x + 8f, y + 2f, paint(7f, secondary, 500))
                        c.drawRoundRect(RectF(x, top, x + cardW, top + cardH), 6f, 6f, stroke(alpha(separator, 0.2f), 0.5f))
                    }
                }
            }
        }

        private fun placeholderKnockout(groups: List<String>): List<Block> {
            val pairs = max(1, groups.size / 2)
            val rowH = 4f + lineH(9f) + 4f
            val pairBoxH = rowH * 2 + 0.5f
            val semisH = lineH(9f) + 6f + pairs * 2 * (pairBoxH + 6f)
            return listOf(Block(max(semisH, 80f) + 10f) { c, _, top ->
                var x = contentX
                fun box(lines: List<String>, bx: Float, by: Float, w: Float, color: Int) {
                    lines.forEachIndexed { i, s -> text(c, s, bx + 6f, by + i * (rowH + 0.5f) + 4f, paint(9f, color)) }
                    c.drawLine(bx, by + rowH, bx + w, by + rowH, stroke(dividerColor, 0.5f))
                    c.drawRoundRect(RectF(bx, by, bx + w, by + pairBoxH), 4f, 4f, stroke(alpha(separator, 0.3f), 0.5f))
                }
                text(c, "SEMI FINAL", x, top, paint(9f, accent, 900))
                var y = top + lineH(9f) + 6f
                for (idx in 0 until pairs) {
                    val g1 = groups[idx * 2]
                    val g2 = if (idx * 2 + 1 < groups.size) groups[idx * 2 + 1] else g1
                    box(listOf("1st Group $g1", "2nd Group $g2"), x, y, 140f, black); y += pairBoxH + 6f
                    box(listOf("1st Group $g2", "2nd Group $g1"), x, y, 140f, black); y += pairBoxH + 6f
                }
                x += 140f + 12f
                val ay = top + 40f
                val ap = stroke(alpha(accent, 0.5f), 1f)
                c.drawLine(x, ay, x + 10f, ay, ap); c.drawLine(x + 6f, ay - 3f, x + 10f, ay, ap); c.drawLine(x + 6f, ay + 3f, x + 10f, ay, ap)
                x += 10f + 12f
                text(c, "FINAL", x, top, paint(9f, accent, 900))
                box(listOf("TBD", "TBD"), x, top + lineH(9f) + 6f, 100f, tertiary)
                x += 100f + 12f
                drawChampion(c, x, top + 4f, 16f)
            })
        }

        // ── Matches tab (pdfMatchesContent) ───────────────────────────────────

        private fun matchRow(m: Match, size: Float, scoreSize: Float, boldWinners: Boolean, monoScore: Boolean, pad: Float): Block {
            val h = pad + lineH(size) + pad
            return Block(h) { c, _, top ->
                val done = finished(m)
                val pA = paint(size, black, if (boldWinners && aWon(m)) 700 else 400)
                val pB = paint(size, black, if (boldWinners && bWon(m)) 700 else 400)
                val score = if (done) "${m.scoreA ?: 0} - ${m.scoreB ?: 0}" else "vs"
                val pS = if (done) paint(scoreSize, black, 700, mono = monoScore) else paint(if (monoScore) 9f else scoreSize, secondary, if (monoScore) 400 else 700)
                val cx = contentX + contentW / 2
                val half = contentW / 2 - pS.measureText(score) / 2 - 8f
                text(c, fit(nameA(m), pA, half), contentX, top + pad, pA)
                text(c, score, cx, top + pad + (lineH(size) - lineH(pS.textSize)) / 2, pS, Paint.Align.CENTER)
                text(c, fit(nameB(m), pB, half), contentX + contentW, top + pad, pB, Paint.Align.RIGHT)
            }
        }

        fun matchesContent(): List<Block> {
            val blocks = mutableListOf<Block>()
            val grouped = input.matches.filter { it.groupLabel != null }.groupBy { it.groupLabel!! }.toSortedMap()
            if (grouped.isNotEmpty()) {
                grouped.forEach { (label, ms) ->
                    blocks += sectionTitle("GROUP $label", orange, 11f, trackingPt = 1f).let { Block(it.height - 4f, it.draw) }
                    ms.sortedWith(compareBy({ it.round ?: 0 }, { it.bracketPosition ?: 0 })).forEach {
                        blocks += matchRow(it, 10f, 10f, boldWinners = true, monoScore = true, pad = 1f)
                    }
                    blocks += spacer(14f)
                }
                val knockout = input.matches.filter { it.groupLabel == null }
                if (knockout.isNotEmpty()) {
                    blocks += sectionTitle("KNOCKOUT STAGE", green, 11f, trackingPt = 1f, topPad = 4f).let { Block(it.height - 4f, it.draw) }
                    knockout.groupBy { it.round ?: 0 }.toSortedMap().forEach { (round, ms) ->
                        blocks += Block(lineH(10f) + 4f) { c, _, top -> text(c, roundName(round), contentX, top, paint(10f, accent, 700)) }
                        ms.sortedBy { it.bracketPosition ?: 0 }.forEach {
                            blocks += matchRow(it, 10f, 9f, boldWinners = false, monoScore = false, pad = 1f)
                        }
                        blocks += spacer(4f)
                    }
                }
            } else {
                rounds.forEach { (round, ms) ->
                    blocks += Block(lineH(11f) + 4f) { c, _, top -> text(c, "Round $round", contentX, top, paint(11f, accent, 700)) }
                    ms.forEach { blocks += matchRow(it, 10f, 10f, boldWinners = true, monoScore = true, pad = 2f) }
                    blocks += Block(10f) { c, _, top -> c.drawLine(contentX, top + 4f, contentX + contentW, top + 4f, stroke(dividerColor, 0.5f)) }
                }
            }
            return blocks
        }

        // ── Standings tab (same tables as the Standings sub-tab) ──────────────

        fun standingsContent(): List<Block> = when (t.matchFormat) {
            MatchFormat.SINGLE_ELIMINATION, MatchFormat.DOUBLE_ELIMINATION -> bracketTable(input.bracketProgress)
            MatchFormat.GROUP_KNOCKOUT -> {
                if (input.groupStandings.isEmpty()) {
                    listOf(emptyText("Standings will appear once group matches are completed."))
                } else {
                    val blocks = mutableListOf<Block>()
                    input.groupStandings.keys.sorted().forEachIndexed { i, group ->
                        if (i > 0) blocks += spacer(20f)
                        blocks += Block(lineH(12f) + 8f) { c, _, top -> text(c, "GROUP $group", contentX, top, paint(12f, accent, 900, tracking = 2f)) }
                        blocks += groupTable(input.groupStandings[group].orEmpty(), t.formatConfig.advancingPerGroup)
                        blocks += caption(input.groupTieBreakCaption)
                    }
                    if (input.matches.any { it.groupLabel == null }) {
                        blocks += spacer(20f)
                        blocks += bracketTable(input.bracketProgress)
                    }
                    blocks
                }
            }
            else -> rrTable(input.rrStandings).let { table ->
                if (input.rrStandings.isEmpty()) table else table + caption(input.rrTieBreakCaption)
            }
        }

        /** How ties are broken, under a standings table (iOS `tieBreakCaption`). */
        fun caption(s: String): Block = Block(8f + lineH(11f)) { c, _, top -> text(c, s, contentX + 4f, top + 8f, paint(11f, gray)) }

        fun emptyText(s: String) = Block(32f + lineH(13f) + 32f) { c, _, top -> text(c, s, contentX + 32f, top + 32f, paint(13f, gray)) }

        private class Col(val title: String, val width: Float?, val align: Paint.Align = Paint.Align.CENTER)

        /** One table row: background, optional rounded ends, and cells laid out like the on-screen Row. */
        private fun tableRow(
            cols: List<Col>, height: Float, radius: Float, isFirst: Boolean, isLast: Boolean,
            bg: Int?, dividerInset: Float?, alphaMul: Float = 1f,
            cell: (Canvas, Int, Float, Float, Float) -> Unit,
        ): Block = Block(height) { c, _, top ->
            val l = contentX; val r = contentX + contentW; val b = top + height
            val rr = floatArrayOf(
                if (isFirst) radius else 0f, if (isFirst) radius else 0f, if (isFirst) radius else 0f, if (isFirst) radius else 0f,
                if (isLast) radius else 0f, if (isLast) radius else 0f, if (isLast) radius else 0f, if (isLast) radius else 0f,
            )
            val shape = Path().apply { addRoundRect(RectF(l, top, r, b), rr, Path.Direction.CW) }
            c.drawPath(shape, fill(Color.WHITE))
            if (bg != null) c.drawPath(shape, fill(bg))
            // Fixed columns are laid out right-to-left; the flexible TEAM column takes the rest.
            val pad = 12f
            val fixed = cols.sumOf { (it.width ?: 0f).toDouble() }.toFloat()
            val flexW = contentW - 2 * pad - fixed
            var x = l + pad
            cols.forEachIndexed { i, col ->
                val w = col.width ?: flexW
                if (alphaMul < 1f) {
                    val layer = c.saveLayerAlpha(RectF(x, top, x + w, b), (alphaMul * 255).toInt())
                    cell(c, i, x, w, top)
                    c.restoreToCount(layer)
                } else {
                    cell(c, i, x, w, top)
                }
                x += w
            }
            if (dividerInset != null && !isLast) c.drawLine(l + dividerInset, b, r, b, stroke(dividerColor, 0.5f))
            // Shell border (gray 10%) on the sides, plus the rounded top / bottom edges.
            val border = stroke(alpha(gray, 0.1f), 1f)
            c.drawLine(l, top + (if (isFirst) radius else 0f), l, b - (if (isLast) radius else 0f), border)
            c.drawLine(r, top + (if (isFirst) radius else 0f), r, b - (if (isLast) radius else 0f), border)
            if (isFirst) {
                c.drawArc(RectF(l, top, l + 2 * radius, top + 2 * radius), 180f, 90f, false, border)
                c.drawLine(l + radius, top, r - radius, top, border)
                c.drawArc(RectF(r - 2 * radius, top, r, top + 2 * radius), 270f, 90f, false, border)
            }
            if (isLast) {
                c.drawArc(RectF(l, b - 2 * radius, l + 2 * radius, b), 90f, 90f, false, border)
                c.drawLine(l + radius, b, r - radius, b, border)
                c.drawArc(RectF(r - 2 * radius, b - 2 * radius, r, b), 0f, 90f, false, border)
            }
        }

        private fun cellText(c: Canvas, s: String, x: Float, w: Float, top: Float, rowH: Float, p: Paint, align: Paint.Align) {
            val tx = when (align) { Paint.Align.LEFT -> x; Paint.Align.RIGHT -> x + w; else -> x + w / 2 }
            text(c, fit(s, p, w), tx, top + (rowH - lineH(p.textSize)) / 2, p, align)
        }

        private fun diffColor(v: Int) = when { v > 0 -> accent; v < 0 -> red; else -> gray }
        private fun signed(v: Int) = if (v > 0) "+$v" else "$v"

        private val bySets get() = t.sportType.ranksStandingsBySets
        private fun diffTitles() = if (bySets) listOf("SETS", "GMS") else listOf("+/-")
        private fun diffValues(e: StandingsEntry) = if (bySets) listOf(e.setDiff, e.pointDiff) else listOf(e.pointDiff)

        /** iOS `roundRobinStandingsTable`. */
        fun rrTable(entries: List<StandingsEntry>): List<Block> {
            if (entries.isEmpty()) return listOf(emptyText("Standings will appear once matches are completed."))
            val stats = if (bySets) listOf("P", "W", "L") else listOf("P", "W", "L", "D")
            val cols = listOf(Col("#", 28f), Col("TEAM", null, Paint.Align.LEFT)) +
                stats.map { Col(it, 28f) } + Col("PTS", 36f) + diffTitles().map { Col(it, 36f) }
            val headH = 8f + lineH(9f) + 8f
            val rowH = 10f + lineH(12f) + 10f
            val blocks = mutableListOf<Block>()
            blocks += tableRow(cols, headH, 16f, true, false, gray6, null) { c, i, x, w, top ->
                cellText(c, cols[i].title, x, w, top, headH, paint(9f, gray, 700), cols[i].align)
            }
            entries.forEachIndexed { idx, e ->
                val values = (if (bySets) listOf(e.played, e.wins, e.losses) else listOf(e.played, e.wins, e.losses, e.draws))
                val diffs = diffValues(e)
                blocks += tableRow(cols, rowH, 16f, false, idx == entries.lastIndex,
                    if (idx % 2 == 0) null else alpha(gray6, 0.4f), 40f) { c, i, x, w, top ->
                    when {
                        i == 0 -> cellText(c, "${idx + 1}", x, w, top, rowH, paint(12f, if (idx < 3) accent else black, 700), Paint.Align.CENTER)
                        i == 1 -> cellText(c, e.teamName, x, w, top, rowH, paint(12f, black, 500), Paint.Align.LEFT)
                        i < 2 + values.size -> cellText(c, "${values[i - 2]}", x, w, top, rowH, paint(11f), Paint.Align.CENTER)
                        i == 2 + values.size -> cellText(c, "${e.points}", x, w, top, rowH, paint(11f, black, 700), Paint.Align.CENTER)
                        else -> { val v = diffs[i - 3 - values.size]; cellText(c, signed(v), x, w, top, rowH, paint(11f, diffColor(v)), Paint.Align.CENTER) }
                    }
                }
            }
            return blocks
        }

        /** iOS group table inside `groupKnockoutStandingsContent`. */
        fun groupTable(entries: List<StandingsEntry>, advancing: Int): List<Block> {
            val cols = listOf(Col("#", 28f), Col("TEAM", null, Paint.Align.LEFT), Col("P", 28f), Col("W", 28f), Col("L", 28f), Col("PTS", 36f)) +
                diffTitles().map { Col(it, 36f) }
            val headH = 8f + lineH(10f) + 8f
            val rowH = 10f + lineH(12f) + 10f
            val blocks = mutableListOf<Block>()
            blocks += tableRow(cols, headH, 12f, true, entries.isEmpty(), gray6, null) { c, i, x, w, top ->
                cellText(c, cols[i].title, x, w, top, headH, paint(10f, gray, 700), cols[i].align)
            }
            entries.forEachIndexed { idx, e ->
                val adv = idx < advancing
                val color = if (adv) accent else black
                val diffs = diffValues(e)
                blocks += tableRow(cols, rowH, 12f, false, idx == entries.lastIndex,
                    if (adv) alpha(accent, 0.04f) else null, 0f) { c, i, x, w, top ->
                    when (i) {
                        0 -> cellText(c, "${idx + 1}", x, w, top, rowH, paint(12f, color, 500), Paint.Align.CENTER)
                        1 -> cellText(c, e.teamName, x, w, top, rowH, paint(12f, color, 500), Paint.Align.LEFT)
                        2 -> cellText(c, "${e.played}", x, w, top, rowH, paint(12f, black, 500), Paint.Align.CENTER)
                        3 -> cellText(c, "${e.wins}", x, w, top, rowH, paint(12f, black, 500), Paint.Align.CENTER)
                        4 -> cellText(c, "${e.losses}", x, w, top, rowH, paint(12f, black, 500), Paint.Align.CENTER)
                        5 -> cellText(c, "${e.points}", x, w, top, rowH, paint(12f, color, 700), Paint.Align.CENTER)
                        else -> { val v = diffs[i - 6]; cellText(c, signed(v), x, w, top, rowH, paint(12f, diffColor(v), 500), Paint.Align.CENTER) }
                    }
                }
            }
            return blocks
        }

        /** iOS `bracketStandingsTable`. */
        fun bracketTable(entries: List<BracketStandingsEntry>): List<Block> {
            if (entries.isEmpty()) return listOf(emptyText("Bracket progress will appear once matches are completed."))
            val cols = listOf(Col("#", 28f), Col("TEAM", null, Paint.Align.LEFT), Col("W", 30f), Col("ROUND", 60f), Col("STATUS", 72f, Paint.Align.RIGHT))
            val headH = 8f + lineH(9f) + 8f
            val rowH = 10f + lineH(12f) + 10f
            val blocks = mutableListOf<Block>()
            blocks += tableRow(cols, headH, 16f, true, false, gray6, null) { c, i, x, w, top ->
                cellText(c, cols[i].title, x, w, top, headH, paint(9f, gray, 700), cols[i].align)
            }
            entries.forEachIndexed { idx, e ->
                val roundLabel = if (input.totalBracketRounds > 0) Match.bracketRoundName(e.maxRound, input.totalBracketRounds) else "R${e.maxRound}"
                blocks += tableRow(cols, rowH, 16f, false, idx == entries.lastIndex,
                    if (idx % 2 == 0) null else alpha(gray6, 0.4f), 40f, if (e.eliminated) 0.6f else 1f) { c, i, x, w, top ->
                    when (i) {
                        0 -> cellText(c, "${idx + 1}", x, w, top, rowH, paint(12f, if (e.eliminated) gray else accent, 700), Paint.Align.CENTER)
                        1 -> cellText(c, e.teamName, x, w, top, rowH, paint(12f, black, 500), Paint.Align.LEFT)
                        2 -> cellText(c, "${e.wins}", x, w, top, rowH, paint(11f), Paint.Align.CENTER)
                        3 -> cellText(c, roundLabel, x, w, top, rowH, paint(10f), Paint.Align.CENTER)
                        else -> cellText(c, if (e.eliminated) "Eliminated" else "Active", x, w, top, rowH,
                            paint(10f, if (e.eliminated) alpha(red, 0.7f) else accent, 700), Paint.Align.RIGHT)
                    }
                }
            }
            return blocks
        }
    }

    // ── Misc ─────────────────────────────────────────────────────────────────

    private fun toastFailure(context: Context) {
        Toast.makeText(context, "Couldn't create the PDF", Toast.LENGTH_SHORT).show()
    }

    private tailrec fun Context.findActivity(): Activity? = when (this) {
        is Activity -> this
        is ContextWrapper -> baseContext.findActivity()
        else -> null
    }
}
