package com.s2aglobal.tournmate.ui.screen.tournament

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowCircleRight
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Description
import androidx.compose.material.icons.filled.EditNote
import androidx.compose.material.icons.outlined.Stadium
import androidx.compose.material.icons.outlined.WarningAmber
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.alpha
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.s2aglobal.tournmate.domain.model.*
import com.s2aglobal.tournmate.ui.screen.tournament.draw.*
import com.s2aglobal.tournmate.ui.theme.AppAccent
import com.s2aglobal.tournmate.ui.theme.WarningOrange
import com.s2aglobal.tournmate.util.BracketPdfPrinter

private val Indigo = Color(0xFF5856D6)
private val Gray6 = Color(0xFFF2F2F7)

/** Score actions the match cards and draw views can trigger. */
internal class MatchActions(
    val isCreator: Boolean,
    val uid: String?,
    val onEnterSetScore: (Match) -> Unit,
    val onEnterSimpleScore: (Match) -> Unit,
    val onConfirm: (Match) -> Unit,
    val onDispute: (Match) -> Unit,
    val onResolveDispute: (Match) -> Unit,
    val onEditSetScore: (Match) -> Unit,
    val onEditSimpleScore: (Match) -> Unit,
) {
    fun isMine(match: Match): Boolean = uid != null && match.isParticipant(uid)

    fun canConfirm(match: Match): Boolean = (isMine(match) && match.submittedBy != uid) || isCreator

    /** Tap on a draw / bracket card. */
    fun onDrawTap(match: Match) {
        when (match.status) {
            MatchStatus.SCHEDULED -> if (isCreator || isMine(match)) onEnterSetScore(match)
            MatchStatus.SCORE_SUBMITTED -> if (isCreator) onConfirm(match)
            MatchStatus.DISPUTED -> if (isCreator) onResolveDispute(match)
            MatchStatus.FINISHED -> Unit
        }
    }
}

private enum class MatchSubTab { DRAW, MATCHES, STANDINGS }

private val MatchFormat.isElimination: Boolean
    get() = this == MatchFormat.SINGLE_ELIMINATION || this == MatchFormat.DOUBLE_ELIMINATION

@Composable
internal fun MatchesTabContent(
    state: TournamentDetailUiState,
    viewModel: TournamentDetailViewModel,
    actions: MatchActions,
) {
    val tournament = state.tournament ?: return
    var subTab by remember { mutableStateOf(MatchSubTab.DRAW) }
    var selectedRound by remember { mutableStateOf<Int?>(null) }
    val context = LocalContext.current

    if (state.matches.isEmpty()) {
        Column(
            Modifier.fillMaxWidth().padding(40.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(16.dp),
        ) {
            Icon(Icons.Outlined.Stadium, null, Modifier.size(48.dp), tint = Color.Gray.copy(alpha = 0.3f))
            Text("No matches yet", fontSize = 16.sp, fontWeight = FontWeight.Bold, color = Color.Gray)
            Text(
                "Matches will appear here once they are generated by the organizer.",
                fontSize = 12.sp, color = Color.Gray, textAlign = TextAlign.Center,
            )
        }
        return
    }

    val drawLabel = if (tournament.matchFormat.isElimination) "Bracket" else "Draw"

    Column(Modifier.fillMaxWidth()) {
        Row(Modifier.fillMaxWidth().padding(bottom = 12.dp), verticalAlignment = Alignment.CenterVertically) {
            Row(Modifier.weight(1f).padding(horizontal = 4.dp).clip(RoundedCornerShape(12.dp)).background(Gray6)) {
                SubTabButton(drawLabel, subTab == MatchSubTab.DRAW, Modifier.weight(1f)) { subTab = MatchSubTab.DRAW }
                SubTabButton("Matches", subTab == MatchSubTab.MATCHES, Modifier.weight(1f)) { subTab = MatchSubTab.MATCHES }
                SubTabButton("Standings", subTab == MatchSubTab.STANDINGS, Modifier.weight(1f)) { subTab = MatchSubTab.STANDINGS }
            }
            Row(
                Modifier.padding(start = 8.dp).clip(CircleShape).background(AppAccent.copy(alpha = 0.1f))
                    .clickable {
                        val tabName = when (subTab) {
                            MatchSubTab.DRAW -> drawLabel
                            MatchSubTab.MATCHES -> "Matches"
                            MatchSubTab.STANDINGS -> "Standings"
                        }
                        BracketPdfPrinter.print(context, tournament, state.matches, state.registrations, tabName)
                    }
                    .padding(horizontal = 12.dp, vertical = 8.dp),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(5.dp),
            ) {
                Icon(Icons.Default.Description, null, Modifier.size(12.dp), tint = AppAccent)
                Text("PDF", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = AppAccent)
            }
        }

        when (subTab) {
            MatchSubTab.DRAW -> DrawContent(state, viewModel, actions)
            MatchSubTab.MATCHES -> when (tournament.matchFormat) {
                MatchFormat.SINGLE_ELIMINATION, MatchFormat.DOUBLE_ELIMINATION ->
                    BracketMatchesContent(state, actions, selectedRound) { selectedRound = it }
                MatchFormat.GROUP_KNOCKOUT -> GroupKnockoutMatchesContent(state, actions)
                else -> RoundRobinMatchesContent(state, actions, selectedRound) { selectedRound = it }
            }
            MatchSubTab.STANDINGS -> StandingsContent(state, viewModel)
        }
    }
}

@Composable
private fun SubTabButton(title: String, active: Boolean, modifier: Modifier, onClick: () -> Unit) {
    Box(
        modifier.clip(RoundedCornerShape(10.dp)).background(if (active) AppAccent.copy(alpha = 0.1f) else Color.Transparent)
            .clickable(onClick = onClick).padding(vertical = 10.dp),
        contentAlignment = Alignment.Center,
    ) {
        Text(title, fontSize = 13.sp, fontWeight = FontWeight.Bold, color = if (active) AppAccent else Color.Gray)
    }
}

// ── Draw ─────────────────────────────────────────────

@Composable
private fun DrawContent(state: TournamentDetailUiState, viewModel: TournamentDetailViewModel, actions: MatchActions) {
    val tournament = state.tournament ?: return
    val rounds = state.allMatchesByRound
    val tap: (Match) -> Unit = { actions.onDrawTap(it) }
    when (tournament.matchFormat) {
        MatchFormat.SINGLE_ELIMINATION -> BracketDrawView(rounds, state.totalBracketRounds, tap)
        MatchFormat.DOUBLE_ELIMINATION -> DoubleEliminationDrawView(rounds, state.totalBracketRounds, tap)
        MatchFormat.GROUP_KNOCKOUT -> GroupKnockoutDrawView(rounds, state.totalBracketRounds, tap)
        MatchFormat.SWISS -> SwissDrawView(
            rounds = rounds,
            currentSwissRound = state.currentSwissRound,
            isOrganizer = state.isCreator,
            canGenerateNextRound = !state.isSwissComplete,
            isLoading = state.isLoading,
            onTapMatch = tap,
            onGenerateNextRound = { viewModel.generateNextSwissRound() },
        )
        MatchFormat.MANUAL_DRAW -> ManualDrawView(rounds, state.formedTeams, tap)
        MatchFormat.ROUND_ROBIN -> RoundRobinDrawView(rounds, tournament.formatConfig.pointsPerWin, tournament.formatConfig.pointsPerLoss, tap)
    }
}

// ── Matches lists ────────────────────────────────────

@Composable
private fun RoundChips(labels: List<Pair<Int, String>>, active: Int, onSelect: (Int) -> Unit) {
    Row(Modifier.horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
        labels.forEach { (round, label) ->
            val isActive = round == active
            Text(
                label, fontSize = 12.sp, fontWeight = FontWeight.Bold,
                color = if (isActive) Color.White else Color.Gray,
                modifier = Modifier.clip(RoundedCornerShape(20.dp))
                    .background(if (isActive) AppAccent else Color.Gray.copy(alpha = 0.1f))
                    .clickable { onSelect(round) }
                    .padding(horizontal = 16.dp, vertical = 8.dp),
            )
        }
    }
}

@Composable
private fun BracketMatchesContent(state: TournamentDetailUiState, actions: MatchActions, selected: Int?, onSelect: (Int) -> Unit) {
    val rounds = state.allMatchesByRound
    val active = selected?.takeIf { s -> rounds.any { it.round == s } } ?: rounds.lastOrNull()?.round ?: 1
    Column(verticalArrangement = Arrangement.spacedBy(20.dp)) {
        RoundChips(rounds.map { it.round to Match.bracketRoundName(it.round, state.totalBracketRounds) }, active, onSelect)

        if (active == 1 && rounds.firstOrNull()?.round == 1) {
            val byes = state.byeTeamNames
            if (byes.isNotEmpty()) {
                Column(
                    Modifier.fillMaxWidth().clip(RoundedCornerShape(14.dp)).background(AppAccent.copy(alpha = 0.06f)).padding(14.dp),
                    verticalArrangement = Arrangement.spacedBy(8.dp),
                ) {
                    Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                        Icon(Icons.Default.ArrowCircleRight, null, Modifier.size(14.dp), tint = AppAccent)
                        Text("${byes.size} team${if (byes.size == 1) "" else "s"} advance with a bye", fontSize = 13.sp, fontWeight = FontWeight.Bold, color = AppAccent)
                    }
                    byes.forEach { Text("• $it", fontSize = 12.sp, color = Color.Gray) }
                }
            }
        }

        rounds.firstOrNull { it.round == active }?.let { group ->
            Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {
                group.matches.forEach { BracketMatchCard(it, actions) }
            }
        }
    }
}

@Composable
private fun RoundRobinMatchesContent(state: TournamentDetailUiState, actions: MatchActions, selected: Int?, onSelect: (Int) -> Unit) {
    val grouped = state.matches.groupBy { it.round ?: 0 }
    val sortedRounds = grouped.keys.sorted()
    val active = selected?.takeIf { it in grouped } ?: sortedRounds.firstOrNull() ?: 1
    Column(verticalArrangement = Arrangement.spacedBy(20.dp)) {
        RoundChips(sortedRounds.map { it to "Round $it" }, active, onSelect)
        grouped[active]?.let { matches ->
            Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                matches.forEach { RoundRobinMatchCard(it, actions) }
            }
        }
    }
}

@Composable
private fun StageLabel(text: String, color: Color) {
    Text(
        text, fontSize = 12.sp, fontWeight = FontWeight.ExtraBold, letterSpacing = 2.sp, color = color,
        modifier = Modifier.clip(RoundedCornerShape(8.dp)).background(color.copy(alpha = 0.08f)).padding(horizontal = 12.dp, vertical = 6.dp),
    )
}

@Composable
private fun GroupKnockoutMatchesContent(state: TournamentDetailUiState, actions: MatchActions) {
    val groupMatches = state.matches.filter { it.groupLabel != null }
    val knockout = state.matches.filter { it.groupLabel == null }
    Column(verticalArrangement = Arrangement.spacedBy(20.dp)) {
        groupMatches.groupBy { it.groupLabel ?: "?" }.toSortedMap().forEach { (group, matches) ->
            Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                StageLabel("GROUP $group", AppAccent)
                matches.forEach { RoundRobinMatchCard(it, actions) }
            }
        }
        if (knockout.isNotEmpty()) {
            Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                StageLabel("KNOCKOUT STAGE", WarningOrange)
                knockout.groupBy { it.round ?: 0 }.toSortedMap().values.forEach { roundMatches ->
                    roundMatches.forEach { RoundRobinMatchCard(it, actions) }
                }
            }
        }
    }
}

private fun matchStatusText(match: Match): String = when (match.status) {
    MatchStatus.FINISHED -> "Completed"
    MatchStatus.SCORE_SUBMITTED -> "Pending Confirm"
    MatchStatus.DISPUTED -> "Disputed"
    MatchStatus.SCHEDULED -> "Upcoming"
}

/** iOS `Match.displayScoreLine`. */
internal fun iosScoreLine(match: Match): String {
    if (match.setScores.isNotEmpty()) {
        val sets = match.setScores.joinToString(", ") { "${it.teamAPoints}-${it.teamBPoints}" }
        return "$sets (${match.setsWonByA}-${match.setsWonByB})"
    }
    val a = match.scoreA
    val b = match.scoreB
    if (a == null || b == null) {
        return when (match.status) {
            MatchStatus.SCORE_SUBMITTED -> "Awaiting Confirmation"
            MatchStatus.DISPUTED -> "Score Disputed ⚠️"
            MatchStatus.FINISHED -> "Finished"
            MatchStatus.SCHEDULED -> "Scheduled"
        }
    }
    return "$a - $b"
}

@Composable
private fun MatchCardShell(mine: Boolean, barColor: Color, spacing: Dp, content: @Composable ColumnScope.() -> Unit) {
    Row(
        Modifier
            .fillMaxWidth()
            .shadow(3.dp, RoundedCornerShape(16.dp), ambientColor = Color.Black.copy(alpha = 0.03f), spotColor = Color.Black.copy(alpha = 0.03f))
            .clip(RoundedCornerShape(16.dp))
            .background(if (mine) AppAccent.copy(alpha = 0.03f) else Color.White)
            .border(if (mine) 1.5.dp else 1.dp, if (mine) AppAccent.copy(alpha = 0.3f) else Color.Gray.copy(alpha = 0.1f), RoundedCornerShape(16.dp))
            .height(IntrinsicSize.Min),
    ) {
        Box(Modifier.width(4.dp).fillMaxHeight().background(barColor))
        Column(Modifier.weight(1f).padding(16.dp), verticalArrangement = Arrangement.spacedBy(spacing), content = content)
    }
}

@Composable
private fun YourMatchBadge() {
    Text(
        "YOUR MATCH", fontSize = 8.sp, fontWeight = FontWeight.ExtraBold, letterSpacing = 0.5.sp, color = Color.White,
        modifier = Modifier.clip(RoundedCornerShape(4.dp)).background(AppAccent).padding(horizontal = 6.dp, vertical = 3.dp),
    )
}

@Composable
private fun BracketMatchCard(match: Match, actions: MatchActions) {
    val mine = actions.isMine(match)
    MatchCardShell(mine, if (mine) AppAccent else Indigo, 12.dp) {
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            Text("MATCH #${match.bracketPosition?.let { "${it + 1}" } ?: "?"}", fontSize = 10.sp, fontWeight = FontWeight.Bold, color = Color.Gray)
            if (mine) YourMatchBadge()
            Spacer(Modifier.weight(1f))
            Text(
                matchStatusText(match).uppercase(), fontSize = 10.sp, fontWeight = FontWeight.Bold,
                color = if (match.status == MatchStatus.FINISHED) AppAccent else Indigo,
            )
        }
        Row(verticalAlignment = Alignment.CenterVertically) {
            TeamBracketLabel(registrationShortName(match.teamA), isRight = false, Modifier.weight(1f))
            Text("VS", fontSize = 10.sp, fontWeight = FontWeight.Bold, color = Color.Gray.copy(alpha = 0.3f), modifier = Modifier.padding(horizontal = 8.dp))
            TeamBracketLabel(registrationShortName(match.teamB), isRight = true, Modifier.weight(1f))
        }
        if (match.status == MatchStatus.FINISHED) {
            Text(iosScoreLine(match), fontSize = 12.sp, fontWeight = FontWeight.Bold, color = AppAccent, textAlign = TextAlign.Center, modifier = Modifier.fillMaxWidth())
        }
        BracketMatchActions(match, actions)
    }
}

@Composable
private fun TeamBracketLabel(name: String, isRight: Boolean, modifier: Modifier) {
    Row(modifier, verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp, if (isRight) Alignment.End else Alignment.Start)) {
        if (!isRight) Box(Modifier.size(24.dp).clip(RoundedCornerShape(4.dp)).background(Color.Gray.copy(alpha = 0.1f)))
        Text(name, fontSize = 13.sp, fontWeight = FontWeight.Bold, maxLines = 1, overflow = TextOverflow.Ellipsis, modifier = Modifier.weight(1f, fill = false))
        if (isRight) Box(Modifier.size(24.dp).clip(RoundedCornerShape(4.dp)).background(Color.Gray.copy(alpha = 0.1f)))
    }
}

@Composable
private fun ActionLink(text: String, color: Color, icon: ImageVector? = null, onClick: () -> Unit) {
    Row(Modifier.clickable(onClick = onClick).padding(vertical = 2.dp), verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(4.dp)) {
        icon?.let { Icon(it, null, Modifier.size(12.dp), tint = color) }
        Text(text, fontSize = 10.sp, fontWeight = FontWeight.Bold, color = color)
    }
}

@Composable
private fun ConfirmDisputeRow(match: Match, actions: MatchActions) {
    if (!actions.canConfirm(match)) return
    Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
        ActionLink("CONFIRM", AppAccent) { actions.onConfirm(match) }
        ActionLink("DISPUTE", Color.Red) { actions.onDispute(match) }
    }
}

@Composable
private fun BracketMatchActions(match: Match, actions: MatchActions) {
    when (match.status) {
        MatchStatus.SCHEDULED -> if (actions.isCreator || actions.isMine(match)) {
            ActionLink("ENTER SCORE", AppAccent, Icons.Default.EditNote) { actions.onEnterSetScore(match) }
        }
        MatchStatus.SCORE_SUBMITTED -> ConfirmDisputeRow(match, actions)
        MatchStatus.DISPUTED -> if (actions.isCreator) {
            ActionLink("RESOLVE DISPUTE", WarningOrange, Icons.Outlined.WarningAmber) { actions.onResolveDispute(match) }
        }
        MatchStatus.FINISHED -> if (actions.isCreator) {
            ActionLink("EDIT SCORE", Color.Gray, Icons.Default.EditNote) { actions.onEditSetScore(match) }
        }
    }
}

@Composable
private fun RoundRobinMatchCard(match: Match, actions: MatchActions) {
    val mine = actions.isMine(match)
    MatchCardShell(mine, AppAccent, 8.dp) {
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            Text(
                "${registrationFullName(match.teamA)} vs ${registrationFullName(match.teamB)}".uppercase(),
                fontSize = 10.sp, fontWeight = FontWeight.Bold, color = Color.Gray,
                maxLines = 1, overflow = TextOverflow.Ellipsis, modifier = Modifier.weight(1f, fill = false),
            )
            if (mine) YourMatchBadge()
            Spacer(Modifier.weight(1f))
            Text(
                matchStatusText(match).uppercase(), fontSize = 10.sp, fontWeight = FontWeight.Bold,
                color = if (match.status == MatchStatus.FINISHED) AppAccent else WarningOrange,
            )
        }
        Text(iosScoreLine(match), fontSize = 14.sp, fontWeight = FontWeight.Bold, color = if (match.status == MatchStatus.FINISHED) AppAccent else Color.Black)

        when (match.status) {
            MatchStatus.SCHEDULED -> if (actions.isCreator || mine) {
                ActionLink("ENTER SCORE", AppAccent, Icons.Default.EditNote) { actions.onEnterSimpleScore(match) }
            }
            MatchStatus.SCORE_SUBMITTED -> ConfirmDisputeRow(match, actions)
            MatchStatus.DISPUTED -> if (actions.isCreator) {
                ActionLink("RESOLVE DISPUTE", WarningOrange, Icons.Outlined.WarningAmber) { actions.onResolveDispute(match) }
            }
            MatchStatus.FINISHED -> Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                match.winnerRegistration?.let { winner ->
                    Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                        Icon(Icons.Default.CheckCircle, null, Modifier.size(12.dp), tint = AppAccent)
                        Text("Winner: ${registrationShortName(winner)}", fontSize = 12.sp, fontWeight = FontWeight.Bold, color = AppAccent)
                    }
                }
                if (actions.isCreator) {
                    Spacer(Modifier.weight(1f))
                    ActionLink("EDIT", Color.Gray, Icons.Default.EditNote) { actions.onEditSimpleScore(match) }
                }
            }
        }
    }
}

// ── Standings ────────────────────────────────────────

@Composable
private fun StandingsContent(state: TournamentDetailUiState, viewModel: TournamentDetailViewModel) {
    val tournament = state.tournament ?: return
    when (tournament.matchFormat) {
        MatchFormat.SINGLE_ELIMINATION, MatchFormat.DOUBLE_ELIMINATION -> BracketStandingsTable(viewModel.computeBracketProgress(state), state.totalBracketRounds)
        MatchFormat.GROUP_KNOCKOUT -> {
            val groups = viewModel.computeGroupStandings(state)
            if (groups.isEmpty()) {
                EmptyStandings("Standings will appear once group matches are completed.")
            } else {
                Column(verticalArrangement = Arrangement.spacedBy(20.dp)) {
                    val advancing = tournament.formatConfig.advancingPerGroup
                    groups.keys.sorted().forEach { group ->
                        Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                            Text("GROUP $group", fontSize = 12.sp, fontWeight = FontWeight.ExtraBold, letterSpacing = 2.sp, color = AppAccent)
                            GroupStandingsTable(groups[group].orEmpty(), advancing)
                        }
                    }
                    if (state.hasKnockoutMatches) BracketStandingsTable(viewModel.computeBracketProgress(state), state.totalBracketRounds)
                }
            }
        }
        else -> RoundRobinStandingsTable(viewModel.computeRRStandings(state))
    }
}

@Composable
private fun EmptyStandings(text: String) {
    Text(text, fontSize = 13.sp, color = Color.Gray, modifier = Modifier.padding(32.dp))
}

@Composable
private fun TableShell(radius: Dp, content: @Composable ColumnScope.() -> Unit) {
    Column(
        Modifier.fillMaxWidth().clip(RoundedCornerShape(radius)).background(Color.White)
            .border(1.dp, Color.Gray.copy(alpha = 0.1f), RoundedCornerShape(radius)),
        content = content,
    )
}

@Composable
private fun HeaderCell(text: String, width: Dp?, modifier: Modifier = Modifier, align: TextAlign = TextAlign.Center, size: Int = 9) {
    Text(
        text, fontSize = size.sp, fontWeight = FontWeight.Bold, color = Color.Gray, textAlign = align,
        modifier = if (width != null) modifier.width(width) else modifier,
    )
}

@Composable
private fun RoundRobinStandingsTable(entries: List<StandingsEntry>) {
    TableShell(16.dp) {
        if (entries.isEmpty()) {
            EmptyStandings("Standings will appear once matches are completed.")
            return@TableShell
        }
        Row(Modifier.fillMaxWidth().background(Gray6).padding(horizontal = 12.dp, vertical = 8.dp)) {
            HeaderCell("#", 28.dp)
            HeaderCell("TEAM", null, Modifier.weight(1f), TextAlign.Start)
            listOf("P", "W", "L", "D").forEach { HeaderCell(it, 28.dp) }
            HeaderCell("PTS", 36.dp)
            HeaderCell("+/-", 36.dp)
        }
        entries.forEachIndexed { idx, e ->
            Row(
                Modifier.fillMaxWidth().background(if (idx % 2 == 0) Color.Transparent else Gray6.copy(alpha = 0.4f)).padding(horizontal = 12.dp, vertical = 10.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                Text("${idx + 1}", fontSize = 12.sp, fontWeight = FontWeight.Bold, color = if (idx < 3) AppAccent else Color.Black, textAlign = TextAlign.Center, modifier = Modifier.width(28.dp))
                Text(e.teamName, fontSize = 12.sp, fontWeight = FontWeight.Medium, maxLines = 1, overflow = TextOverflow.Ellipsis, modifier = Modifier.weight(1f))
                listOf(e.played, e.wins, e.losses, e.draws).forEach {
                    Text("$it", fontSize = 11.sp, textAlign = TextAlign.Center, modifier = Modifier.width(28.dp))
                }
                Text("${e.points}", fontSize = 11.sp, fontWeight = FontWeight.Bold, textAlign = TextAlign.Center, modifier = Modifier.width(36.dp))
                Text(
                    if (e.pointDiff > 0) "+${e.pointDiff}" else "${e.pointDiff}",
                    fontSize = 11.sp, textAlign = TextAlign.Center, modifier = Modifier.width(36.dp),
                    color = when { e.pointDiff > 0 -> AppAccent; e.pointDiff < 0 -> Color.Red; else -> Color.Gray },
                )
            }
            if (idx < entries.size - 1) HorizontalDivider(Modifier.padding(start = 40.dp), color = Color(0xFFE5E5EA))
        }
    }
}

@Composable
private fun GroupStandingsTable(entries: List<StandingsEntry>, advancingCount: Int) {
    TableShell(12.dp) {
        Row(Modifier.fillMaxWidth().background(Gray6).padding(horizontal = 12.dp, vertical = 8.dp)) {
            HeaderCell("#", 28.dp, size = 10)
            HeaderCell("TEAM", null, Modifier.weight(1f), TextAlign.Start, size = 10)
            listOf("P", "W", "L").forEach { HeaderCell(it, 28.dp, size = 10) }
            HeaderCell("PTS", 36.dp, size = 10)
        }
        entries.forEachIndexed { index, e ->
            val advances = index < advancingCount
            val color = if (advances) AppAccent else Color.Black
            Row(
                Modifier.fillMaxWidth().background(if (advances) AppAccent.copy(alpha = 0.04f) else Color.Transparent).padding(horizontal = 12.dp, vertical = 10.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                Text("${index + 1}", fontSize = 12.sp, fontWeight = FontWeight.Medium, color = color, textAlign = TextAlign.Center, modifier = Modifier.width(28.dp))
                Text(e.teamName, fontSize = 12.sp, fontWeight = FontWeight.Medium, color = color, maxLines = 1, overflow = TextOverflow.Ellipsis, modifier = Modifier.weight(1f))
                listOf(e.played, e.wins, e.losses).forEach {
                    Text("$it", fontSize = 12.sp, fontWeight = FontWeight.Medium, textAlign = TextAlign.Center, modifier = Modifier.width(28.dp))
                }
                Text("${e.points}", fontSize = 12.sp, fontWeight = FontWeight.Bold, color = color, textAlign = TextAlign.Center, modifier = Modifier.width(36.dp))
            }
            HorizontalDivider(color = Color(0xFFE5E5EA))
        }
    }
}

@Composable
private fun BracketStandingsTable(entries: List<BracketStandingsEntry>, totalRounds: Int) {
    TableShell(16.dp) {
        if (entries.isEmpty()) {
            EmptyStandings("Bracket progress will appear once matches are completed.")
            return@TableShell
        }
        Row(Modifier.fillMaxWidth().background(Gray6).padding(horizontal = 12.dp, vertical = 8.dp)) {
            HeaderCell("#", 28.dp)
            HeaderCell("TEAM", null, Modifier.weight(1f), TextAlign.Start)
            HeaderCell("W", 30.dp)
            HeaderCell("ROUND", 60.dp)
            HeaderCell("STATUS", 72.dp, align = TextAlign.End)
        }
        entries.forEachIndexed { idx, e ->
            Row(
                Modifier.fillMaxWidth().alpha(if (e.eliminated) 0.6f else 1f)
                    .background(if (idx % 2 == 0) Color.Transparent else Gray6.copy(alpha = 0.4f))
                    .padding(horizontal = 12.dp, vertical = 10.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                Text("${idx + 1}", fontSize = 12.sp, fontWeight = FontWeight.Bold, color = if (e.eliminated) Color.Gray else AppAccent, textAlign = TextAlign.Center, modifier = Modifier.width(28.dp))
                Text(e.teamName, fontSize = 12.sp, fontWeight = FontWeight.Medium, maxLines = 1, overflow = TextOverflow.Ellipsis, modifier = Modifier.weight(1f))
                Text("${e.wins}", fontSize = 11.sp, textAlign = TextAlign.Center, modifier = Modifier.width(30.dp))
                Text(
                    if (totalRounds > 0) Match.bracketRoundName(e.maxRound, totalRounds) else "R${e.maxRound}",
                    fontSize = 10.sp, textAlign = TextAlign.Center, maxLines = 1, modifier = Modifier.width(60.dp),
                )
                Text(
                    if (e.eliminated) "Eliminated" else "Active", fontSize = 10.sp, fontWeight = FontWeight.Bold,
                    color = if (e.eliminated) Color.Red.copy(alpha = 0.7f) else AppAccent, textAlign = TextAlign.End, modifier = Modifier.width(72.dp),
                )
            }
            if (idx < entries.size - 1) HorizontalDivider(Modifier.padding(start = 40.dp), color = Color(0xFFE5E5EA))
        }
    }
}
